# Generated by Django 3.2.7 on 2021-10-07 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_pk', models.CharField(default='85357fe32de14d55beafb4e8a4d746fc', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('author', models.JSONField(editable=False)),
                ('id', models.CharField(editable=False, max_length=200)),
                ('type', models.CharField(default='post', editable=False, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('contentType', models.CharField(choices=[('', 'text/markdown'), ('', 'text/plain'), ('', 'application/base64'), ('', 'image/png;base64'), ('', 'image/jpeg;base64'), ('', 'HTML')], editable=False, max_length=20)),
                ('categories', models.CharField(choices=[('web', 'Web'), ('tutorial', 'Tutorial'), ('', '')], editable=False, max_length=20)),
                ('count', models.PositiveBigIntegerField()),
                ('size', models.PositiveBigIntegerField()),
                ('comments', models.JSONField(default='null')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(max_length=20)),
                ('unlisted', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
