# Generated by Django 3.2.7 on 2021-10-07 21:46

import Posts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_pk', models.CharField(default='8241406bce06437895bf194245e6bb95', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('author', models.JSONField(editable=False)),
                ('id', models.CharField(editable=False, max_length=200)),
                ('type', models.CharField(default='post', editable=False, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('contentType', models.CharField(choices=[('markdown', 'text/markdown'), ('plain', 'text/plain'), ('app', 'application/base64'), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64'), ('html', 'HTML')], editable=False, max_length=20)),
                ('content', Posts.models.Base64Field(db_column='content')),
                ('categories', models.CharField(choices=[('web', 'Web'), ('tutorial', 'Tutorial'), ('', '')], editable=False, max_length=20)),
                ('count', models.PositiveBigIntegerField()),
                ('size', models.PositiveBigIntegerField()),
                ('comments', models.JSONField(default='null')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(max_length=20)),
                ('unlisted', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
