# Generated by Django 3.2.7 on 2021-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='5fac2226f89144ff9ef8e3c56b129487', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
