# Generated by Django 3.2.7 on 2021-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20211103_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_pk',
            field=models.CharField(default='63246b48b0fb44229d132812bbacf9ac', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
