# Generated by Django 3.2.7 on 2021-10-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_post_post_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='077c430b41a444a2a7282d344133b930', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
