# Generated by Django 3.2.7 on 2021-11-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_comments_comment_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_pk',
            field=models.CharField(default='2e779e3867964269923096070b771054', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
