# Generated by Django 3.2.7 on 2021-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_post_post_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='4d1758abbd75436599085a2fd2957fc5', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
