# Generated by Django 3.2.7 on 2021-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_comments_comment_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_pk',
            field=models.CharField(default='d2efc0c79e8e4b32b4a9dddb3a9de01a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
