# Generated by Django 3.2.7 on 2021-10-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20211008_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_id',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='0860485d1c494c229ab9cb639409b325', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
