# Generated by Django 3.2.7 on 2021-11-22 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_comments_comment_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Post_pk_str',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='auth_pk_str',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Post_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Posts.post'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_pk',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
