# Generated by Django 3.2.7 on 2021-10-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20211009_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='d1e9870fe98e45179e3177823d8b2367', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
