# Generated by Django 3.2.7 on 2021-10-09 06:50

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20211009_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=Posts.models.Base64Field(db_column='content', default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='afa23485ba5145c99114150dfb2e2ea9', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
