# Generated by Django 3.2.7 on 2021-10-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_auto_20211009_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='2ffc4208040c48808e744d241e924043', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
