# Generated by Django 3.2.7 on 2021-10-11 17:27

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_alter_post_post_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=Posts.models.Base64Field(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='dc1752ef918649b38acd5900db197963', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
