# Generated by Django 3.2.7 on 2021-10-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_auto_20211011_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments_id',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pk',
            field=models.CharField(default='c2814c755cfb4cf683d411ae366364c9', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
