# Generated by Django 3.2.7 on 2021-12-01 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('type', models.CharField(default='like', editable=False, max_length=30)),
                ('object', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('auth_pk', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('id', models.CharField(editable=False, max_length=200, unique=True)),
                ('type', models.CharField(default='author', editable=False, max_length=30)),
                ('host', models.CharField(default='https://linkedspace-staging.herokuapp.com/', max_length=200)),
                ('displayName', models.CharField(max_length=50)),
                ('url', models.CharField(editable=False, max_length=200)),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('type', models.CharField(default='followers', editable=False, max_length=30)),
                ('auth_pk', models.OneToOneField(default='42a4aa2a30c14f0388b4517de1ef84ed', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Author.author')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='liked', editable=False, max_length=30)),
                ('items', models.ManyToManyField(blank=True, default=list, to='Author.Like')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='auth_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='follow', editable=False, max_length=30)),
                ('summary', models.CharField(max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('auth_pk', models.OneToOneField(default='c66e058af5214f1b953b0fcadc40cc53', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Author.author')),
                ('type', models.CharField(default='inbox', editable=False, max_length=30)),
                ('items', models.JSONField(blank=True, default=list)),
                ('iFollows', models.ManyToManyField(blank=True, default=list, to='Author.FriendRequest')),
                ('iLikes', models.ManyToManyField(blank=True, default=list, to='Author.Like')),
            ],
        ),
    ]
