# Generated by Django 3.2.7 on 2021-12-01 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.TextField(editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=500, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.TextField(default='https://linkedspace-staging.herokuapp.com/', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.TextField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.TextField(default='author', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.TextField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='followers',
            name='auth_pk',
            field=models.OneToOneField(default='74a8f59cbee947dda6446259b50f72e0', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='auth_pk',
            field=models.OneToOneField(default='509c091323094eaf8f29aaf7f760fcd3', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
