# Generated by Django 3.2.7 on 2021-12-01 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='auth_pk',
            field=models.OneToOneField(default='7286860ce8604583876a8c29001b46b1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='auth_pk',
            field=models.OneToOneField(default='de5cd69748aa4ef19aedb043b4410f7a', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
