# Generated by Django 3.2.7 on 2021-12-02 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='auth_pk',
            field=models.OneToOneField(default='ee47502628e04a209368ccf3c4c3bab5', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='auth_pk',
            field=models.OneToOneField(default='65f0a89799f64ec3b613658991a70525', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
