# Generated by Django 3.2.7 on 2021-12-01 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0004_auto_20211201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='auth_pk',
            field=models.OneToOneField(default='f31e73c0029d4bcc890680741546b6a5', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='auth_pk',
            field=models.OneToOneField(default='1cb97e1f071d41e98c2eed59f89e1526', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
