# Generated by Django 3.2.7 on 2021-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('id', models.CharField(default='http://127.0.0.1:8000/author/670a03809ff0401281bb70e4e66a1766', editable=False, max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(default='author', editable=False, max_length=30)),
                ('host', models.CharField(default='http://127.0.0.1:8000/', max_length=200)),
                ('displayName', models.CharField(max_length=50)),
                ('url', models.CharField(default='http://127.0.0.1:8000/author/670a03809ff0401281bb70e4e66a1766', editable=False, max_length=200)),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
