# Generated by Django 3.2.7 on 2021-10-26 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('auth_pk', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('id', models.CharField(editable=False, max_length=200, unique=True)),
                ('type', models.CharField(default='author', editable=False, max_length=30)),
                ('host', models.CharField(default='http://127.0.0.1:8000/', max_length=200)),
                ('displayName', models.CharField(max_length=50)),
                ('url', models.CharField(editable=False, max_length=200)),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('is_admin_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('context', models.CharField(max_length=200)),
                ('like_id', models.CharField(default='53201ca38731453791ee1f3ef20d6b13', editable=False, max_length=200, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200)),
                ('type', models.CharField(default='like', editable=False, max_length=30)),
                ('object', models.CharField(max_length=200)),
                ('auth_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('auth_pk', models.OneToOneField(default='c0d04715840543b0aca4fce407b7fca5', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Author.author')),
                ('type', models.CharField(default='inbox', editable=False, max_length=30)),
                ('items', models.JSONField(blank=True, default=list)),
                ('iLikes', models.ManyToManyField(blank=True, default=list, to='Author.Like')),
            ],
        ),
    ]
