# Generated by Django 3.2.7 on 2021-10-20 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_inbox_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.CharField(default='169a08f2d57147f29d996aa0026eb629', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='http://127.0.0.1:8000/author/169a08f2d57147f29d996aa0026eb629', editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/author/169a08f2d57147f29d996aa0026eb629', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='auth_pk',
            field=models.OneToOneField(default='1b7eddf97c9b49c59e571352b2b23e80', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
