# Generated by Django 3.2.7 on 2021-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0004_auto_20211007_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.CharField(default='2bb719dec5cf4425bcc0fa125e7bfc76', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='http://127.0.0.1:8000/author/2bb719dec5cf4425bcc0fa125e7bfc76', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/author/2bb719dec5cf4425bcc0fa125e7bfc76', editable=False, max_length=200),
        ),
    ]
