# Generated by Django 3.2.7 on 2021-11-19 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0004_alter_inbox_auth_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='id',
        ),
        migrations.AddField(
            model_name='followers',
            name='auth_pk',
            field=models.OneToOneField(default='4f1e0f9318b249bfad52c3282c01cb63', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='items',
            field=models.ManyToManyField(blank=True, default=list, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='auth_pk',
            field=models.OneToOneField(default='01f5f38fae4144bb87ff5e8fdf35c30c', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
