# Generated by Django 3.2.7 on 2021-10-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0005_auto_20211008_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.CharField(default='2194d722334f487c9caf666df1584b5a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='http://127.0.0.1:8000/author/2194d722334f487c9caf666df1584b5a', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/author/2194d722334f487c9caf666df1584b5a', editable=False, max_length=200),
        ),
    ]
