# Generated by Django 3.2.7 on 2021-11-24 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0007_auto_20211122_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='auth_pk',
            field=models.OneToOneField(default='d8fac66e8a8148b6bb8cf4e7743ea290', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='auth_pk',
            field=models.OneToOneField(default='7883215cb7424a1b830dd5db61cff6c1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
