# Generated by Django 3.2.7 on 2021-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0008_auto_20211009_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.CharField(default='85ee4c03cd6342f0989095eb9a59fac0', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='http://127.0.0.1:8000/author/85ee4c03cd6342f0989095eb9a59fac0', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/author/85ee4c03cd6342f0989095eb9a59fac0', editable=False, max_length=200),
        ),
    ]
