# Generated by Django 3.2.7 on 2021-10-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0009_auto_20211009_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.CharField(default='6acce6cef7b445358dd8da9101066e79', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='http://127.0.0.1:8000/author/6acce6cef7b445358dd8da9101066e79', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/author/6acce6cef7b445358dd8da9101066e79', editable=False, max_length=200),
        ),
    ]
