# Generated by Django 3.2.7 on 2021-10-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0010_auto_20211009_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.CharField(default='3bc97374dbff4a3ebb0fb7d756909b89', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='http://127.0.0.1:8000/author/3bc97374dbff4a3ebb0fb7d756909b89', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/author/3bc97374dbff4a3ebb0fb7d756909b89', editable=False, max_length=200),
        ),
    ]
