# Generated by Django 3.2.7 on 2021-10-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0011_auto_20211011_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_pk',
            field=models.CharField(default='e71e4b451d8b4baf875511d2dfc25084', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='http://127.0.0.1:8000/author/e71e4b451d8b4baf875511d2dfc25084', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/author/e71e4b451d8b4baf875511d2dfc25084', editable=False, max_length=200),
        ),
    ]
